### ISSUE TITLE
esp_idf_lib_helpers really necessary?

### ISSUE THREAD

**Issue by mateustoin** [m5stack/MPU6886-idf#1]
> #include <esp_idf_lib_helpers.h>

This include is really necessary? When I was trying to use the lib, I was not able to find this headers and the code seems to be working fine without this include. What is it for?

**Comment by rashedtalukder** [comment]
Was used in dev and not anymore. Fixed in 636fb7e6c40796222e765b09e298d7f27ed0f4ad
